# Generated by Django 5.1 on 2024-09-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.TextField()),
                ('company_url', models.URLField()),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=254)),
                ('status', models.BooleanField(default=True)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('OTP', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_validation', models.BooleanField(default=False)),
            ],
        ),
    ]
