# Generated by Django 5.1 on 2024-09-04 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('bot_type', models.CharField(choices=[('chatbot', 'Chatbot'), ('voicebot', 'Voicebot')], max_length=50)),
                ('launcher_text', models.CharField(blank=True, max_length=255, null=True)),
                ('to_emails', models.TextField(help_text='Comma-separated list of emails')),
                ('trigger_time', models.DateTimeField()),
                ('trigger_time_mobile', models.DateTimeField()),
                ('font_object', models.JSONField(blank=True, default=dict, null=True)),
                ('font', models.CharField(blank=True, max_length=100, null=True)),
                ('theme', models.CharField(blank=True, max_length=100, null=True)),
                ('access_url_themes', models.URLField(blank=True, max_length=500, null=True)),
                ('customer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
