# Generated by Django 5.1 on 2024-09-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
