# Generated by Django 5.1 on 2024-09-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_bot_is_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='company_logo',
            field=models.ImageField(blank=True, default='company_logos/default_logo.png', null=True, upload_to='company_logos/'),
        ),
    ]
