# Generated by Django 5.1 on 2024-09-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_bot_company_logo_url_bot_font_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='font',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
