# Generated by Django 4.1.13 on 2024-10-03 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_bot_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='action',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='default_language',
            field=models.CharField(blank=True, default='en', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='language_code',
            field=models.CharField(default='en', max_length=15),
        ),
        migrations.AddField(
            model_name='bot',
            name='multi_lingual_switch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bot',
            name='preference_statement',
            field=models.TextField(default='english'),
        ),
        migrations.CreateModel(
            name='ChatbotQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(max_length=100)),
                ('alternate_question_text', models.TextField(blank=True, null=True)),
                ('auto_slide', models.CharField(default='0', max_length=10)),
                ('default_options', models.TextField(blank=True, null=True)),
                ('error_jump_question_id', models.IntegerField(blank=True, null=True)),
                ('error_text', models.TextField(blank=True, null=True)),
                ('flow_id', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_ai_available', models.CharField(default='0', max_length=10)),
                ('is_feedback', models.CharField(default='0', max_length=10)),
                ('is_set_dynamic', models.CharField(default='0', max_length=10)),
                ('is_skip', models.CharField(default='0', max_length=10)),
                ('logical_jump', models.CharField(default='0', max_length=10)),
                ('next_question_id', models.IntegerField(blank=True, null=True)),
                ('send_mail', models.CharField(default='0', max_length=10)),
                ('sequence', models.IntegerField()),
                ('session_variable_name', models.CharField(blank=True, max_length=255, null=True)),
                ('xPos', models.CharField(blank=True, max_length=10, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('yPos', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.bot')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
