# Generated by Django 4.1.13 on 2024-10-04 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_chatbot_chatbotquestion_chatbot_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=15)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='users.bot')),
            ],
        ),
    ]
