# Generated by Django 4.1.13 on 2024-10-05 11:46

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_botlanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='office_from_timing',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='office_timezone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='office_to_timing',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='office_weekdays',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
