# Generated by Django 5.1.1 on 2024-10-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_bot_trigger_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='customer_profile',
        ),
        migrations.RemoveField(
            model_name='botlanguage',
            name='chatbot',
        ),
        migrations.DeleteModel(
            name='ChatbotQuestion',
        ),
        migrations.DeleteModel(
            name='Bot',
        ),
        migrations.DeleteModel(
            name='BotLanguage',
        ),
    ]
