# Generated by Django 5.1.1 on 2024-10-07 09:21

import django.db.models.deletion
import jsonfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('company_logo', models.ImageField(blank=True, default='company_logos/default_logo.png', null=True, upload_to='company_logos/')),
                ('company_logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('bot_type', models.CharField(choices=[('chatbot', 'Chatbot'), ('voicebot', 'Voicebot')], max_length=50)),
                ('launcher_text', models.CharField(blank=True, max_length=255, null=True)),
                ('to_emails', models.TextField(help_text='Comma-separated list of emails')),
                ('trigger_time', models.IntegerField(blank=True, default=0, null=True)),
                ('trigger_time_mobile', models.IntegerField(default=0)),
                ('action', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('font_object', models.JSONField(blank=True, default=dict, null=True)),
                ('font', models.CharField(blank=True, max_length=300, null=True)),
                ('font_size', models.CharField(blank=True, default='14px', max_length=10, null=True)),
                ('theme', models.CharField(blank=True, max_length=255, null=True)),
                ('access_url_themes', models.URLField(blank=True, max_length=500, null=True)),
                ('launcher_position', models.CharField(blank=True, default='RB', max_length=5, null=True)),
                ('view_setup_object', models.JSONField(blank=True, default=dict, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('default_language', models.CharField(blank=True, default='en', max_length=15, null=True)),
                ('multi_lingual_switch', models.BooleanField(default=False)),
                ('language_code', models.CharField(default='en', max_length=15)),
                ('preference_statement', models.TextField(default='english')),
                ('office_from_timing', models.TimeField(blank=True, null=True)),
                ('office_to_timing', models.TimeField(blank=True, null=True)),
                ('office_weekdays', jsonfield.fields.JSONField(blank=True, null=True)),
                ('office_timezone', models.CharField(blank=True, max_length=10, null=True)),
                ('customer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bot_create',
            },
        ),
        migrations.CreateModel(
            name='BotLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=15)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='bots.bot')),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(max_length=100)),
                ('alternate_question_text', models.TextField(blank=True, null=True)),
                ('auto_slide', models.CharField(default='0', max_length=10)),
                ('default_options', models.TextField(blank=True, null=True)),
                ('error_jump_question_id', models.IntegerField(blank=True, null=True)),
                ('error_text', models.TextField(blank=True, null=True)),
                ('flow_id', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_ai_available', models.CharField(default='0', max_length=10)),
                ('is_feedback', models.CharField(default='0', max_length=10)),
                ('is_set_dynamic', models.CharField(default='0', max_length=10)),
                ('is_skip', models.CharField(default='0', max_length=10)),
                ('logical_jump', models.CharField(default='0', max_length=10)),
                ('next_question_id', models.IntegerField(blank=True, null=True)),
                ('send_mail', models.CharField(default='0', max_length=10)),
                ('sequence', models.IntegerField()),
                ('session_variable_name', models.CharField(blank=True, max_length=255, null=True)),
                ('xPos', models.CharField(blank=True, max_length=10, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('yPos', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chatbot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.bot')),
            ],
            options={
                'db_table': 'Questions',
                'ordering': ['sequence'],
            },
        ),
    ]
