# Generated by Django 5.1.1 on 2024-10-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_bot_banned_ips_bot_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='consent_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bot',
            name='consent_enabled_for_euro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bot',
            name='consent_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
