# Generated by Django 5.1.1 on 2024-10-15 06:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_bot_consent_enabled_bot_consent_enabled_for_euro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
