# Generated by Django 5.1.1 on 2024-10-18 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_bot_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_email', models.EmailField(max_length=254, unique=True)),
                ('agent_name', models.CharField(max_length=255)),
                ('agent_password', models.CharField(max_length=255)),
                ('agent_number', models.CharField(blank=True, max_length=15)),
                ('livechat_redirect_whatsapp', models.BooleanField(default=False)),
                ('agent_avatar', models.URLField(blank=True, null=True)),
                ('chats_limit', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bots', models.ManyToManyField(related_name='agents', to='bots.bot')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents_as_department', to='bots.bot')),
            ],
        ),
    ]
