# Generated by Django 5.1.1 on 2024-10-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
